name: "Coverage check"
description: "A GitHub Action that check minimum coverage percentage!"
author: Miguel Savignano
branding:
  icon: "check-square"
  color: "green"
inputs:
  type:
    description: "lcov | simplecov"
    required: true
    default: "lcov"
  token:
    description: "Github token for create checks"
    required: true
  min_coverage:
    description: "Minimum coverage"
    default: "80"
  result_path:
    description: "Json with coverage result"
    required: true
  show_coverage_per_file:
    description: "Show coverage for every file"
    required: false
    default: false
runs:
  using: "docker"
  image: "Dockerfile"
